#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd beta
yarn generate-ids
git add -u src/pages/**/*.md
# we run prettier to format the files before commit and will have a github PR check as well
yarn prettier