contact_links:
  - name: 📃 Bugs in React
    url: https://github.com/facebook/react/issues/new/choose
    about: This issue tracker is not for bugs in React. Please file React issues here.
  - name: 🤔 Questions and Help
    url: https://reactjs.org/community/support.html
    about: This issue tracker is not for support questions. Please refer to the React community's help and discussion forums.
