/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import * as esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const generatedHooksLintOutfile = path.resolve(
  root,
  'src/components/MDX/Sandpack/generatedHooksLint.ts'
);

const stubbedModules = new Set([
  'fs',
  'path',
  'crypto',
  'util',
  'assert',
  '@babel/core',
  '@babel/parser',
  'hermes-parser',
]);

const stubPlugin = {
  name: 'stub-sandpack-hooks-runtime-deps',
  setup(build) {
    build.onResolve({filter: /.*/}, (args) => {
      if (stubbedModules.has(args.path)) {
        return {
          path: args.path,
          namespace: 'sandpack-hooks-stub',
        };
      }
    });

    build.onLoad(
      {filter: /.*/, namespace: 'sandpack-hooks-stub'},
      () => ({
        contents: `
          const stub = new Proxy(function () { return stub; }, {
            get(_target, prop) {
              if (prop === Symbol.toPrimitive) return () => '';
              if (prop === 'toString') return () => '';
              if (prop === 'valueOf') return () => '';
              if (prop === 'then') return undefined;
              return stub;
            },
            apply() { return stub; },
            construct() { return stub; },
          });

          module.exports = stub;
        `,
        loader: 'js',
      })
    );
  },
};

await esbuild.build({
  stdin: {
    contents: `
      const plugin = require('eslint-plugin-react-hooks');

      const rulesOfHooks = plugin.rules['rules-of-hooks'];
      const exhaustiveDeps = plugin.rules['exhaustive-deps'];

      export const reactHooksPlugin = {
        rules: {
          'rules-of-hooks': rulesOfHooks,
          'exhaustive-deps': exhaustiveDeps,
        },
      };
    `,
    resolveDir: root,
    sourcefile: 'sandpack-hooks-entry.js',
  },
  bundle: true,
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  format: 'esm',
  minify: true,
  outfile: generatedHooksLintOutfile,
  platform: 'browser',
  plugins: [stubPlugin],
});

const generatedSource = fs.readFileSync(generatedHooksLintOutfile, 'utf8');
const header = `/* eslint-disable */
// @ts-nocheck
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is generated by scripts/buildSandpackHooksLint.mjs.

`;

fs.writeFileSync(generatedHooksLintOutfile, header + generatedSource);
