/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import {createRequire} from 'module';
import {fileURLToPath} from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const require = createRequire(import.meta.url);

const generatedThemeOutfile = path.resolve(
  root,
  'src/components/MDX/Sandpack/generatedTheme.ts'
);

const tailwindConfig = require(path.resolve(root, 'tailwind.config.js'));

const sandpackThemeFonts = {
  body: tailwindConfig.theme.extend.fontFamily.text
    .join(', ')
    .replace(/"/g, ''),
  mono: tailwindConfig.theme.extend.fontFamily.mono
    .join(', ')
    .replace(/"/g, ''),
  size: tailwindConfig.theme.extend.fontSize.code,
};

const generatedThemeModule = `/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is generated by scripts/buildSandpackTheme.mjs.

export const sandpackThemeFonts = ${JSON.stringify(
  sandpackThemeFonts,
  null,
  2
)} as const;
`;

fs.writeFileSync(generatedThemeOutfile, generatedThemeModule);
